Simplify the epilog but rely on people to write out the return code file properly

diff --git a/scripts/epilog b/scripts/epilog
--- a/scripts/epilog
+++ b/scripts/epilog
@@ -32,15 +32,13 @@ if [ -e /tmp/${JOB_ID}-${SGE_TASK_ID}-return ]; then
 	fi
 	PSQL_CMD="${PSQL_CMD}, returncode = ${RETURNCODE}"
 else
-	# No return code so we don't know whether the code that's been run just
-	# doesn't return one, or if we were rescheduled, so look for it in the
-	# context.  The webUI puts 'rescheduled-$TASK_NO' in the context if it
-	# was done from there.  Is there a better way to do this?
-	RESCHEDULED=`qstat -j ${SGE_ID} 2>/dev/null | grep "rescheduled-${TASK_NO}"`
-	if [ "${RESCHEDULED}" != "" ]; then
-		# If it was rescheduled then just quit as if epilog didn't run
-		exit 0
-	fi
+	# No return code left so the job either died, in which case it shouldn't
+	# run the rest of the epilog, or, we're rescheduled so again, it 
+	# shouldn't run the rest of the epilog
+	# This simplification means that all scripts *MUST* have:
+	# echo $? > /tmp/${JOB_ID}-${SGE_TASK_ID}-return
+	# at the bottom of them
+	exit 0
 fi
 
 # Figure out if it's batch or not and make the appropriate chunk of psql code
